Create user entity when user registers #32
snowy-peak/homely-frontend pull request #37
Opened 2023-10-12 12:45 UTC by AndreiPetrusMihai

2023-10-12 19:02 UTC, Matt757 requested changes

2023-10-13 05:27 UTC, AndreiPetrusMihai commented on src/features/auth/components/LoginForm/useLoginForm.ts
> +  email: Yup.string().email('Invalid email').required(),
Yep, I'll also add the regex here.

2023-10-13 05:29 UTC, AndreiPetrusMihai commented on src/features/auth/components/RegisterForm/useRegisterForm.ts
> +      email: IS_DEV_ENV ? 'register.user@gmail.com' : '',
It's a custom env var, we can create any amount of them. This one is used to decide if the test account credentials should be prefilled on the login form. I guess I can also use the var here.

2023-10-13 05:30 UTC, AndreiPetrusMihai commented on src/features/auth/components/LoginForm/useLoginForm.ts
> +  password: Yup.string().required(),
No, I think it's fine to make the password validation a bit more ambiguous on login.

2023-10-15 16:32 UTC, AndreiPetrusMihai commented on src/auth/guards/client/withRedirectOnAnon.tsx
> +        router.push(redirectTo, undefined, { shallow: true });
This was needed to remove some errors.

2023-10-15 16:32 UTC, AndreiPetrusMihai commented on src/auth/guards/server/getSessionData.ts
> +      isUserInitialized: JSON.parse(isUserInitialized),
JSON.parse(undefined) throws an error, so we need to check first.

2023-10-15 16:32 UTC, AndreiPetrusMihai commented on src/auth/guards/server/withSession.ts
> -    if (!isUnauthed) {
This check was pointless since we already have an `if(isUnauthed)` above which always returns something.

2023-10-15 16:32 UTC, AndreiPetrusMihai commented on src/auth/guards/server/withSessionProps.ts
> +};
The refresh route doesn't need all the logic in the withSession guard. For this reason we created this simplified version which only passes the essential data without processing it in any way.

2023-10-15 16:32 UTC, AndreiPetrusMihai commented on src/common/utils/cookies/cookies.ts
> +): string | undefined =>
Cookies can be undefined if they aren't present in the browser.

2023-10-15 16:32 UTC, AndreiPetrusMihai commented on src/pages/auth/refresh.tsx
> +    return unsubscribe;
This gets called when the component unmounts.

2023-10-15 16:34 UTC, AndreiPetrusMihai commented
Backend PR was merged

2023-10-16 17:19 UTC, AndreiPetrusMihai commented
This will be merged after the workspaces PR. It's unnatural, but it saves us a lot of trouble.

2023-10-16 19:20 UTC, Matt757 approved these changes

2023-10-19 13:15 UTC, merged